
class TokenType:
    GOTO = 'GOTO'
    INTEGER = 'INTEGER'
    STRING = 'STR'
    PLUS = 'PLUS'
    MINUS = 'MINUS'
    MULTIPLICATION = 'MUL'
    DIVIDE = 'DIVIDE'
    PRINT = 'PRINT'
    DEFINE = 'DEF'
    UNEXPECTED_KEYWORD = 'UXK'
    EQUALS = '='
    VARIABLE = 'VAR'
    EOF = 'EOF'